### ISSUE TITLE
Question about object feature, paper motivation and Ask for predicted bbox

### ISSUE THREAD

**Issue by WeitaiKang** [ZzZZCHS/WS-3DVG#2]
Hi authors, thanks for your pioneer job. I have a few questions and need from your support.

1. In the summary of paper intro, you say WS-3DVG only need scene-sentence level pairs, instead of object-sentence annotations. Would you mind to explain further? Since the sentences in ScanRefer, Nr3D/Sr3D are all labeled towards object level, Human need to identify the object, then can they provide the sentence, in the labeling phrase. So it confuses me how it can be treated as "**scene**-sentence level"

2. In your text reconstruction loss, you are using the box features as the Key and Value in the Transformer Decoder. However, it seems that you haven't mentioned how you get these box features. Can you explain more details?

3. Would you mind to provide all the predicted bboxes with their confidence scores of GroupFree in the ScanRefer and Nr3D/Sr3D? I think it would be better for us to follow your work!

4. Could you provide the guideline for prepare sunrgbd data and its corresponding config for run and test?

**Comment by ZzZZCHS** [comment]
1. Object-level labels require bounding box annotations, which are the most labor-intensive part. The term "scene-sentence level" means that we do not need bounding boxes, but the sentences we use are still at the object level (describing one target object).
2. The candidates' features are extracted using the object detector, GroupFree.
3. We use the pretrained weights of GroupFree. Then, the confidence scores are extracted by forwarding through the GroupFree model. (I'm not sure if you are referring to the "[objectness score](https://github.com/ZzZZCHS/WS-3DVG/blob/main/models/groupfree/modules.py#L146)".
4. We didn't use SUN RGB-D data for training. The "SUN" / "SCAN" in our experimental part merely denotes that the object detector is pretrained on SUN RGB-D or ScanNet. These pretrained weights can be directly downloaded from GroupFree's [repo](https://github.com/zeliu98/Group-Free-3D?tab=readme-ov-file#sun-rgb-d).

**Comment by WeitaiKang** [comment]
Oh yea you are right. You are not using the SUN RBGD dataset. Sorry for my mistake.

I have a follow up question. So the pretrained model is the **Ours(L12, O512)** for ScanNet V2 and **Ours(L6, O256)** of SUN RBGD in the GroupFree's repo? I'm wondering which version of pretrained model you are exactly using.

**Comment by ZzZZCHS** [comment]
We used (L6, O256) for both ScanNet and SUN RGBD.

**Comment by WeitaiKang** [comment]
Great! Thanks for your clarification!
