### ISSUE TITLE
Question about Model Reproduction

### ISSUE THREAD

**Issue by Liuuuuuyh** [ZzZZCHS/WS-3DVG#6]
Dear authors. I have reproduced your model following your tutorial, but the results are very poor. After comparing my logs with the training logs you provided, I noticed the biggest difference lies in the _pos_ratio_ and _neg_ratio_. Could you please assist me in identifying where the issue might be?
Mine:
<img width="452" alt="image" src="https://github.com/ZzZZCHS/WS-3DVG/assets/138308044/8d0dcb5f-7349-4657-b592-8ad5957a9f4c">
Yours:
<img width="462" alt="image" src="https://github.com/ZzZZCHS/WS-3DVG/assets/138308044/83924500-c124-4a9d-80d9-5a8bd4fa8261">

**Comment by ZzZZCHS** [comment]
Could you show me the full training logs?

**Comment by Liuuuuuyh** [comment]
[log.txt](https://github.com/ZzZZCHS/WS-3DVG/files/15415142/log.txt)
This is my training log.

**Comment by ZzZZCHS** [comment]
I believe it's because you didn't load the pre-trained GroupFree properly. The "train_iou_max" should not be so low even at the early training stage, as the maximum IoU is determined by the pre-trained GroupFree. You can try downloading the "scannet_l6o256" version from [here](https://drive.google.com/file/d/1aS3vsHtg1QU0yFGPa_-kdBmfGR7VTvY0/view). We apologize for the lack of clarity in the README.

**Comment by Liuuuuuyh** [comment]
I have confirmed that I have downloaded the correct GroupFree model and placed it in the specified location. However, I still cannot obtain results and have noticed that the loaded GroupFree model does not match model.group_free completely. Did you encounter a similar situation before?

**Comment by Liuuuuuyh** [comment]
Thank you very much for your assistance. I have resolved my issue. The problem indeed lied with the GroupFree model. I downloaded the correct model, but during the loading process, I didn't notice the mismatched key names as there was no prompt. After modifying the loaded model's _dict_ I obtained the desired results.

**Comment by ZzZZCHS** [comment]
Oh... I changed the key names in the dict before, but I totally forgot that... Sorry for the inconvenience, and thank you for your response. We'll add this to the README for clearer instructions.
