### ISSUE TITLE
Problem with GLoVE embeddings download link

### ISSUE THREAD

**Issue by swzhang5** [ZzZZCHS/WS-3DVG#7]
Hello, thx for your work. As per the instructions, I am supposed to download the GLoVE embeddings. However, when I click on the provided link [https://kaldir.vc.in.tum.de/glove.p], I am greeted with garbled characters as shown in the image below. I would greatly appreciate it if you could look into this issue and provide a working download link or a solution to this problem.
Thank you!
![Screenshot 2024-12-06 171245](https://github.com/user-attachments/assets/92cebe1e-494e-4520-8327-c631c2430523)

**Comment by ZzZZCHS** [comment]
You can try: `wget https://kaldir.vc.in.tum.de/glove.p`
